"""Added category for Item

Revision ID: 2394396db11e
Revises: 339bc09d2052
Create Date: 2022-11-02 17:38:14.099592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2394396db11e'
down_revision = '339bc09d2052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
